### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by nightfox8** [thtrieu/darkflow#517] opened 2018-01-09 12:20 UTC
Hello All, While creating a new model with own dataset I am getting this error,
Can anyone help?

> Running entirely on CPU
> cfg/tiny-yolo-voc_2c.cfg loss hyper-parameters:
> 	H       = 13
> 	W       = 13
> 	box     = 5
> 	classes = 2
> 	scales  = [1.0, 5.0, 1.0, 1.0]
> Building cfg/tiny-yolo-voc_2c.cfg loss
> Building cfg/tiny-yolo-voc_2c.cfg train op
> 2018-01-09 17:40:06.493071: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
> Finished in 4.2163631916s
> 
> Enter training ...
> 
> cfg/tiny-yolo-voc_2c.cfg parsing train/Annotations
> Parsing for ['green traffic signal', 'red traffic signal'] 
> [====================>]100%  green_signal_21.xml
> Statistics:
> red traffic signal: 18
> green traffic signal: 20
> Dataset size: 37
> Dataset of 37 instance(s)
> Traceback (most recent call last):
>   File "/usr/local/bin/flow", line 6, in <module>
>     exec(compile(open(__file__).read(), __file__, 'exec'))
>   File "/home/sohilparekh/Desktop/HardikC/darkflow/flow", line 6, in <module>
>     cliHandler(sys.argv)
>   File "/home/sohilparekh/Desktop/HardikC/darkflow/darkflow/cli.py", line 29, in cliHandler
>     print('Enter training ...'); tfnet.train()
>   File "/home/sohilparekh/Desktop/HardikC/darkflow/darkflow/net/flow.py", line 39, in train
>     for i, (x_batch, datum) in enumerate(batches):
>   File "/home/sohilparekh/Desktop/HardikC/darkflow/darkflow/net/yolo/data.py", line 113, in shuffle
>     inp, new_feed = self._batch(train_instance)
>   File "/home/sohilparekh/Desktop/HardikC/darkflow/darkflow/net/yolov2/data.py", line 27, in _batch
>     img = self.preprocess(path, allobj)
>   File "/home/sohilparekh/Desktop/HardikC/darkflow/darkflow/net/yolo/predict.py", line 62, in preprocess
>     result = imcv2_affine_trans(im)
>   File "/home/sohilparekh/Desktop/HardikC/darkflow/darkflow/utils/im_transform.py", line 20, in imcv2_affine_trans
>     h, w, c = im.shape
> AttributeError: 'NoneType' object has no attribute 'shape'

I had the image at the specified place,
This is my annotation file,

```
<annotation>
	<folder>Green_Signal</folder>
	<filename>green_signal_21.JPG</filename>
	<path>/home/sohilparekh/Desktop/HardikC/darkflow/train/Images/Green_Signal/green_signal_21.JPG</path>
	<source>
		<database>Unknown</database>
	</source>
	<size>
		<width>4608</width>
		<height>3456</height>
		<depth>3</depth>
	</size>
	<segmented>0</segmented>
	<object>
		<name>traffic signal</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>1635</xmin>
			<ymin>1603</ymin>
			<xmax>2944</xmax>
			<ymax>2319</ymax>
		</bndbox>
	</object>
	<object>
		<name>green traffic signal</name>
		<pose>Unspecified</pose>
		<truncated>0</truncated>
		<difficult>0</difficult>
		<bndbox>
			<xmin>2344</xmin>
			<ymin>1753</ymin>
			<xmax>2802</xmax>
			<ymax>2186</ymax>
		</bndbox>
	</object>
</annotation>
```
Also the image is at the specified path in annotation, please check below image,

![screenshot from 2018-01-09 17-47-44](https://user-images.githubusercontent.com/6474150/34720656-80c7ae88-f565-11e7-9b21-187be2ac958b.png)

Thanks.

**Comment by GuimExc** [comment] 2018-01-09 16:20
Check this comment:
https://github.com/thtrieu/darkflow/issues/265#issuecomment-306089270

**Comment by abagshaw** [comment] 2018-01-10 01:46
Closing as duplicate of https://github.com/thtrieu/darkflow/issues/265

**Closed by abagshaw** 2018-01-10 01:46 UTC
Labels: duplicate

**Comment by prinzmark** [comment] 2019-02-17 08:30
please try to provide comprehensive example for windows 10
