### ISSUE TITLE
Are weights transferable to darknet?

### ISSUE THREAD

**Issue by kieferselmon** [thtrieu/darkflow#548] opened 2018-01-27 23:59 UTC
Is there a way to use weights trained using darkflow on the original darknet framework?

**Comment by abagshaw** [comment] 2018-01-28 22:34
Unfortunately not at the moment.

**Comment by pbabbicola** [comment] 2018-01-29 12:49
Check #198 which explains how to do it. If you can code it you could send a PR.

**Comment by abagshaw** [comment] 2018-01-29 15:02
Closing as duplicate of https://github.com/thtrieu/darkflow/issues/198

**Closed by abagshaw** 2018-01-29 15:02 UTC
Labels: duplicate
