### ISSUE TITLE
re-train yolo.weight  (customer)

### ISSUE THREAD

**Issue by Phoebe-star** [thtrieu/darkflow#520] opened 2018-01-10 09:39 UTC
I want to  use  yolo.weight ( for coco dataset ) for re-training  and the weight is at 
 https://pjreddie.com/media/files/yolo.weights

re-train the Model  command 
./darknet detector train cfg/coco.data cfg/yolo.cfg yolo.weight

Q 1 :   I want to  use yolo.weight  for  initial weight  and  train  my own data ,
          how to prepare the dataset for  the training?
thanks   thanks

**Comment by abagshaw** [comment] 2018-01-10 22:03
Closing as duplicate of https://github.com/thtrieu/darkflow/issues/281

**Closed by abagshaw** 2018-01-10 22:03 UTC
Labels: duplicate

**Comment by Phoebe-star** [comment] 2018-01-12 08:23
it seems like prepare data  for voc  ,  not  coco  data.
because yolo.weight  is  trained  with  coco data ,  not  voc

**Comment by abagshaw** [comment] 2018-01-18 05:47
@Phoebe-star I believe Darkflow uses the voc format for training on any dataset (just a common format to use) - I could be wrong about that though. Either way let's keep this conversation to a single thread. Feel free to post further questions regarding annotation formatting on that issue.
