### ISSUE TITLE
When the model detects objects in a camera, how to output it to a json or any other text format? while monitoring if it finds a person then how to output it?

### ISSUE THREAD

**Issue by kumarvvin** [thtrieu/darkflow#530] opened 2018-01-18 05:35 UTC
I want to build a business logic based on objects detected in camera, like a compliance. how to output the objects detected into a json?

**Comment by abagshaw** [comment] 2018-01-18 05:39
Closing as duplicate of https://github.com/thtrieu/darkflow/issues/505

**Closed by abagshaw** 2018-01-18 05:39 UTC
